sealed abstract class Photo(val boosters: List[Booster])

case object DongFangMingZhuDianShiTa extends Photo(List(AllBooster(0.1)))
case object ShiBoHuiZhongGuoGuan extends Photo(List(AllBooster(0.1)))
case object WaiTan extends Photo(List(BuildingTypeBooster(Commercial, 0.3)))
case object PuDongXinQuZiMaoQu extends Photo(List(BuildingTypeBooster(Industrial, 0.3)))
case object ShanghaiMeiShuDianYingZhiPianChang extends Photo(List(BuildingTypeBooster(Commercial, 0.3)))
case object NanJingChangJiangDaQiao extends Photo(List(AllBooster(0.1)))
case object HuaXiCun extends Photo(List(BuildingTypeBooster(Residential, 0.3)))
case object HuaiYangCai extends Photo(List(BuildingTypeBooster(Residential, 0.3)))
case object YiXingZiShaHu extends Photo(List(BuildingTypeBooster(Commercial, 0.3)))
case object XiHu extends Photo(List(AllBooster(0.1)))
case object YueJu extends Photo(List(AllBooster(0.1)))
case object ShiJieHuLianWangDaHui extends Photo(List(BuildingTypeBooster(Commercial, 0.3)))
case object LuShuiQingShanJiuShiJinShanYinShanLiNian extends Photo(List(AllBooster(0.1)))
